# fly.toml app configuration file generated for virtual-gallery-morning-fire-4767 on 2024-02-15T15:42:18-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'virtual-gallery-morning-fire-4767'
primary_region = 'bos'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
